remove unwanteds at start, add back missing things from old file

diff --git a/system/init b/system/init
--- a/system/init
+++ b/system/init
@@ -28,9 +28,17 @@ echo "" > /tmp/.app-install-fail.log
 ## Disable swap
 ###
 
-if [ $SETUP_TYPE="desktop" ]; then
+if [ $SETUP_TYPE = "desktop" ]; then
     ./disable-swap
 fi;
+
+###
+## Remove stuff
+###
+
+apt-get remove --purge -y rhythmbox
+apt-get autoremove --purge -y
+apt-get autoclean
 
 ###
 ## Update stuff
@@ -52,7 +60,7 @@ apt-get -y upgrade --show-upgraded
 ./app-install openssl;
 ./app-install apt-transport-https;
 
-if [ $SETUP_TYPE="desktop" ]; then
+if [ $SETUP_TYPE = "desktop" ]; then
 
     ./app-install dconf-tools
 
@@ -83,13 +91,17 @@ fi;
 
 # -- Dev UI tools
 
-if [ $SETUP_TYPE="desktop" ]; then
+if [ $SETUP_TYPE = "desktop" ]; then
 
     # Sublime text\
-    SUBL_PRE="wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -";
+    SUBL_PRE="wget -qO - 'https://download.sublimetext.com/sublimehq-pub.gpg' | sudo apt-key add -";
     SUBL_PRE="${SUBL_PRE} && echo 'deb https://download.sublimetext.com/ apt/stable/' | sudo tee /etc/apt/sources.list.d/sublime-text.list"
     SUBL_PRE="${SUBL_PRE} && apt-get update"
-    ./app-install sublime-text "" "${SUBL_PRE}"
+
+    SUBL_POST="mkdir -p '${HOME}/.config/sublime-text-3/Packages/User'"
+    SUBL_POST="${SUBL_POST} && cp ../sublime-user-settings.json '${HOME}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings'"
+
+    ./app-install sublime-text "${SUBL_POST}" "${SUBL_PRE}"
 
 fi;
 
@@ -101,11 +113,6 @@ fi;
 PG_POST="update-rc.d postgresql enable && service postgresql start"
 ./app-install postgresql "${PG_POST}"
 
-if [ $SETUP_TYPE="server" ]; then
-
-    ./app-install letsencrypt
-
-fi;
 
 ###
 ## Terminal setup-ish
@@ -119,11 +126,28 @@ fi;
 ## Some GNOME settings
 ###
 
-[ $SETUP_TYPE="desktop" ] && ./gnome-settings;
+[ $SETUP_TYPE = "desktop" ] && ./gnome-settings;
 
 ###
 ## Create the new ssh keys
 ###
+
+
+###
+## Other/extra?
+###
+
+if [ $SETUP_TYPE = "server" ]; then
+
+    ./app-install letsencrypt
+
+
+    # nano syntax highlighting
+    echo "Setup nano syntax highlighting...";
+    [ -f "./setup-nano-syntax-highlighting" ] && ./setup-nano-syntax-highlighting || echo "File missing - setup-nano-syntax-highlighting";
+
+fi;
+
 
 echo "\n\nSuccessful packages:\n-------------\n"
 [ -e /tmp/.app-install-success.log ] && cat /tmp/.app-install-success.log;
